### ISSUE TITLE
Fishing Reel not reeling in fish...

### ISSUE THREAD

**Issue by DatBoiOmonie** [Lightning-64/Tide#11]
I think it may have to do with lag but here's my log if that helps idk i just can't seem to catch fish in my server and the constant avg tick is like 120 ms. 
[latest.log](https://github.com/user-attachments/files/17181624/latest.log)
 i notice right before im about to reel in a fish, it gives me a log error or something and then it always makes the fish missing noise even tho i tried my best to time it.

**Comment by Lightning-64** [comment]
What version of tide and version of minecraft is this on?

**Comment by Lightning-64** [comment]
According to your log, you are running tide 1.0.0, which isn't supported anymore.

This same issue should be fixed as of 1.3.2 and up!
