### ISSUE TITLE
[Forge 1.20.1] Game crashes after hooking fish

### ISSUE THREAD

**Issue by Svfer6** [Lightning-64/Tide#13]
It can be either the first or the one after the first catch, the game just shuts down completely.

Here's my log 
[crash-2024-09-30_21.20.53-client.txt](https://github.com/user-attachments/files/17198136/crash-2024-09-30_21.20.53-client.txt)

**Comment by padenormous** [comment]
I get the same crash right as I get a bite on the fishing line. 
[crash-2024-09-30_23.53.16-Server.txt](https://github.com/user-attachments/files/17199547/crash-2024-09-30_23.53.16-Server.txt)

**Comment by Lightning-64** [comment]
I'll get this fixed as soon as possible. For now, you can just downgrade to 1.3.3.

**Comment by Lightning-64** [comment]
> I get the same crash right as I get a bite on the fishing line. [crash-2024-09-30_23.53.16-Server.txt](https://github.com/user-attachments/files/17199547/crash-2024-09-30_23.53.16-Server.txt)

This crash is different than the first one referenced by the issue. I'll also put out a fix for this.

**Comment by Svfer6** [comment]
> I'll get this fixed as soon as possible. For now, you can just downgrade to 1.3.2.

Thanks for getting on this so quickly, but sadly that version also has the same issue, will just be waiting for the fix.

**Comment by Lightning-64** [comment]
So I did some testing on a bunch of different versions, but I couldn't replicate the crash for some reason.

Could you possibly give me a list of mods that you are using somehow, and maybe give me some more information about what you are doing when the crash happens? What fishing rod are you using?

**Comment by Svfer6** [comment]
> So I did some testing on a bunch of different versions, but I couldn't replicate the crash for some reason.
> 
> Could you possibly give me a list of mods that you are using somehow, and maybe give me some more information about what you are doing when the crash happens? What fishing rod are you using?

It just happens while using any rod, the game just crashes whenever a fish bites, sometimes it gets past the first catch but on the second attempt it'll crash either way.

Here's a list of my mods
![Screenshot 2024-10-01 185221](https://github.com/user-attachments/assets/d628a2ee-0c4d-4e62-ac95-55d33c961582)
![Screenshot 2024-10-01 185233](https://github.com/user-attachments/assets/e5c8b905-e528-4ac7-93a1-2205a1877c3e)
![Screenshot 2024-10-01 185252](https://github.com/user-attachments/assets/86c98169-fd20-4860-a14f-6c5d23af05ed)
![Screenshot 2024-10-01 185303](https://github.com/user-attachments/assets/6d8c96e4-5ec1-4144-a4a7-6344dde51aa1)
![Screenshot 2024-10-01 185315](https://github.com/user-attachments/assets/f82ecd9d-0696-4d1f-9f0c-ffe906d856dc)
![Screenshot 2024-10-01 185326](https://github.com/user-attachments/assets/b8f48db0-00c9-4f63-bf5f-7e0c20035a7e)
![Screenshot 2024-10-01 185336](https://github.com/user-attachments/assets/1fd2ee6f-321b-4ce6-9217-46e029a0a1e3)
![Screenshot 2024-10-01 185345](https://github.com/user-attachments/assets/b4e54cb1-0b5e-4da8-b5a2-fa1fe9731abf)
![Screenshot 2024-10-01 185357](https://github.com/user-attachments/assets/a84ada57-ce92-4fde-bb4b-51665eddf120)
![Screenshot 2024-10-01 185403](https://github.com/user-attachments/assets/aff5de39-fbab-4fe7-b2de-90fbf65732d6)
![Screenshot 2024-10-01 185210](https://github.com/user-attachments/assets/afc44a5d-698c-4500-a21d-a472e330b04f)

**Comment by Svfer6** [comment]
> So I did some testing on a bunch of different versions, but I couldn't replicate the crash for some reason.
> 
> Could you possibly give me a list of mods that you are using somehow, and maybe give me some more information about what you are doing when the crash happens? What fishing rod are you using?

It just happens while using any rod, the game just crashes whenever a fish bites, sometimes it gets past the first catch but on the second attempt it'll crash either way.

Here's a list of my mods (with tide removed due to crash)

[Mod List.txt](https://github.com/user-attachments/files/17217506/Mod.List.txt)

**Comment by Svfer6** [comment]
After some testing, it appears to be an incompatibility with the recast mod, simply removing recast removes the crash entirely, so I'll just be playing without it from now on. The line being recast automatically is the reason why the first catch doesn't crash but the second does.

**Comment by Lightning-64** [comment]
Alright, that makes sense.

I might actually add a config file setting for auto-recasting the fishing rods so you don't need to download the recast mod, because that does seem like a helpful feature.

**Comment by NotRuRu** [comment]
> Alright, that makes sense.
> 
> I might actually add a config file setting for auto-recasting the fishing rods so you don't need to download the recast mod, because that does seem like a helpful feature.

is this going to be implemented for older versions later on? I'm playing on 1.21.1 and crash seems to happen here as well when both mods are on
