### ISSUE TITLE
[Quilt 1.21] Crash on fish touching bobber

### ISSUE THREAD

**Issue by THEKAI64** [Lightning-64/Tide#14]
I'm using Tide 1.3.3

[crash-2024-10-01_22.21.47-server.txt](https://github.com/user-attachments/files/17216109/crash-2024-10-01_22.21.47-server.txt)

If you don't feel like fixing this because you don't officially support quilt, that's fair.
But, knowing about issues is always better than not, right?

**Comment by THEKAI64** [comment]
rename because bait doesn't seem relevant
always a crash on 1-3 hooks

**Comment by THEKAI64** [comment]
seems to be the same issue as https://github.com/Lightning-64/Tide/issues/13#issue-2557972293

going back to 1.3.2 fixes it

**Comment by Lightning-64** [comment]
This is an issue with certain loot parameters when a crate is fished only being supported forge and neoforge, meaning it would be broken for fabric and such. I'll put out a fixed version soon,

**Comment by Lightning-64** [comment]
Fixed! (as of Tide-1.3.3-fix (FABRIC))

**Comment by THEKAI64** [comment]
nice!
