### ISSUE TITLE
error about a path with a png

### ISSUE THREAD

**Issue by VaporeonScripts** [Lightning-64/Tide#15]
[15:59:09] [Render thread/ERROR] [minecraft/Util]: Invalid path in pack: tide:textures/entity/fish/template - Copy.png, ignoring

**Comment by VaporeonScripts** [comment]
neoforge 1.21.1 .65

**Comment by Lightning-64** [comment]
Just a file that was left behind from when I was adding fish entities. It won’t affect the gameplay at all but I’ll make sure to remove that file next update.

**Comment by VaporeonScripts** [comment]
alright
