### ISSUE TITLE
[FORGE 1.20.1] Custom added fishes through datapack to already existing journal pages doesn't shows in the journal book

### ISSUE THREAD

**Issue by NotCodly** [Lightning-64/Tide#17]
Minecraft : 1.20.1
Tide : 1.3.3

The custom fishes that i added through datapack shows up on the notification but when i opened the journal the fish does not show in the journal book, i have tried restarting both the server and the client and i have tried resetting my unlock with /journal lock. it still doesn't shows up

The fishes shows up in the notification
![bug journal 1](https://github.com/user-attachments/assets/691b6634-2a0d-48a8-a59f-e326c7bc2227)

but when i opened the journal book, it doesn't show
![bug journal 2](https://github.com/user-attachments/assets/9d4bb5d8-dfd9-459b-82bf-3d34dbca80ca)
![bug journal 3](https://github.com/user-attachments/assets/d495bbd3-72ff-4b37-a992-3394686d52d9)

here's one of JSON file
![bug journal 4](https://github.com/user-attachments/assets/e4384184-51a7-4088-8292-655d28d2d007)

**Comment by emihead** [comment]
I can't replicate this. It could be some kind of KubeJS thing?

**Comment by NotCodly** [comment]
i tried it with less mod few minutes ago, with only KubeJs and Tide only. it seems works fine, ill try do restarting the whole server
![image](https://github.com/user-attachments/assets/240f4fda-7599-4a02-b9cb-acd76bd83a5d)

**Comment by NotCodly** [comment]
it seems like its not KubeJs that is incompatible. i'll look into it more about what mod that causing this weird issue

**Comment by NotCodly** [comment]
okay it works on singleplayer but not in multiplayer on dedicated server
![image](https://github.com/user-attachments/assets/1d39010f-51bb-4cde-b9ee-053150eb33e5)

**Comment by NotCodly** [comment]
okay i found the actual problem of it. both the client and the server need to have the same datapack that contains the journal modification. if the client doesn't have it and connected to the server that has journal modification. it will caused the bug to happened

**Comment by NotCodly** [comment]
somehow it works when you load into the singleplayer world first and then connect to the multiplayer
https://www.youtube.com/watch?v=PqDyFg_LTZ4

**Comment by Lightning-64** [comment]
Fixed as of 1.3.4!
