### ISSUE TITLE
Nether Depths Upgrade Issue?

### ISSUE THREAD

**Issue by Sabert25** [Lightning-64/Tide#20]
Good day,

I tried your mod with Nether Depths Upgrade and with Fish of Thieves Mod together and everything seems fine besides being able to catch the fishes from Nether Depths Upgrade mod. I couldnt be able to catch one bye a ton of attempts. Only the one from Tide mod.
The overworld works fine, I can catch fishes from Tide and Fish of Thieves mod without problems.
And all Fishes even from Nether Depths Upgrade get listed in the book. My problem persists just in catching them.
They spawn in the lava aswell. So the Nether Depths Upgrade mod works fine.
Are they really that rare to catch or is something not working with the version of mod im using?
Im using the version 1.3.3 for 1.21 Fabric for tide. And Version 3.1.8 for 1.21 for Nether Depths Upgrade.

Would be gratefull for an anwer, thanks!

Kind Regards

Sabert25

**Comment by Lightning-64** [comment]
I can look into this... I know during testing I had no problems catching the fish from Nether Depths Upgrade, but something might have changed.

As a temporary fix: I think if you craft the lava fishing rod from the Nether Depths Upgrade mod you can guaranteed catch the fish from that mod, but you won't have the fishing minigame or any of that.

**Comment by Sabert25** [comment]
I changed my setup to 1.20.1 fabric and picked up the proper versions for it and tested the thing here on this version. On 1.20.1 on both mods its working. Could catch it with an tide rod like a charm.

**Comment by Lightning-64** [comment]
Fixed as of 1.3.4

**Comment by Sabert25** [comment]
Cool, thanks!--Gesendet mit der WEB.DE Mail AppAm 12.11.24, 19:05 schrieb Lightning64 ***@***.***>:

Fixed as of 1.3.4
