### ISSUE TITLE
Integration with Lootr

### ISSUE THREAD

**Issue by lihaan** [Lightning-64/Tide#21]
Chests spawned in fishing huts are not spawned as Lootr chests. Not so sure if explicit integration has to be added.

Tide 1.3.3-fix-1.20.1
Minecraft 1.20.1
Fabric Loader 16.7

I'm looking forward to putting this as part of a modpack I'm making, and I appreciate that it is getting updated with new features / fixes to improve the overall experience. Thanks!

**Comment by Lightning-64** [comment]
The chests in fishing huts always contain the same loot, and therefore don't have separate loot tables. That's probably why they don't spawn as Lootr chests.

To be honest I kind of forgot fishing huts even exist, but I can definitely add actual chest loot tables in a future update which should fix this issue.
