### ISSUE TITLE
Make bobbers/lines/hooks retrievable if they exist in an item tag

### ISSUE THREAD

**Issue by BrownBear85** [Lightning-64/Tide#24]
I'm the developer for Stardew Fishing, and we are currently developing an update adding multiple functional bobber items that influence our fishing minigame. At the current stage of development, they can be equipped on Aquaculture rods, but we are planning to support tide's Angler's Workshop system in addition. Since tide's bobber/hook/line items are effectively deleted (unretrievable) after being equipped, that conflicts with our existing bobber system. 

I would really appreciate it if you could add an item tag or some other method of configuration for fishing rod equipable items that would define items that should be retrievable (be able to be taken off of a fishing rod after being applied). 

Unrelated, but as someone who just played with your mod for the first time, I personally was disappointed when I realized that you cannot retrieve bobbers/hooks/lines after applying them and I bet a lot of players share my opinion. A configuration option for retrieving these fishing rod equipable items would be a nice bonus if you end up implementing this suggestion/request.

Thanks for your consideration.
I really like your mod and am excited to see how it evolves!

**Comment by Lightning-64** [comment]
Yeah, I can definitely add this! I'll probably just end up making them all retrievable.

**Comment by BrownBear85** [comment]
Amazing, thanks!
