### ISSUE TITLE
Wrong tag for farmers delight compat on forge

### ISSUE THREAD

**Issue by pafeuu** [Lightning-64/Tide#25]
![_farmersdelight_cutting_fish_slice_cutting](https://github.com/user-attachments/assets/0c64104e-ba5c-4395-9a0f-f65956d435e4)
current tag is "c:tools/knives" and should be "forge:tools/knives

**Comment by Lightning-64** [comment]
Yeah, I’m aware of this. It will be fixed in the next update!
