### ISSUE TITLE
[1.20.1] Custom Fish Profile from KubeJs doesn't work

### ISSUE THREAD

**Issue by NotCodly** [Lightning-64/Tide#3]
I added a custom fish item through KubeJS, and I tried adding the fish to the fish profile and it seems like it doesn't works? is this a bug or is this a mistake from my end?
(NOTE: i forgot to mention that i disabled the "doMinigame" rule in both tide and tide-common config file)
 
this is the fish item
![tide_bug1](https://github.com/user-attachments/assets/edb80ba0-42e3-4c17-ae42-4c614664885a)
it doesn't detected here, even though i have the fish in my hotbar
![tide_bug2](https://github.com/user-attachments/assets/8b9bcfb9-dfe7-41b9-9364-83d7bd2e14c1)
this is the tide.toml line
![image](https://github.com/user-attachments/assets/b908e5a6-0a30-4564-b27a-eddb2fda0270)

**Comment by Lightning-64** [comment]
First of all, which version of tide is this on?

If it's 1.2.0 or later, the config files no longer support adding fish to the journal because of how I reworked the mod, and also because I plan on having a datapack system to add profiles in the future instead of doing it directly through the config.

**Comment by NotCodly** [comment]
I'm using 1.3.1 version of Tide. I must've missed the changelog. Sorry about that.

Also that's a great news! Looking forward to the datapack implementation

**Comment by Lightning-64** [comment]
The datapack system is out as of 1.3.2, and a guide on how to make one can be found [here](https://github.com/Lightning-64/Tide/wiki/Modifying-the-journal). I hope you find this helpful!

**Comment by NotCodly** [comment]
Thank you so much! also one more question if you don't mind. Is there any way to modify or add fishing in the lava loot tables? does this work? 
![image](https://github.com/user-attachments/assets/65dad23d-1e23-4f86-9e92-3fd8a65c5a1d)

**Comment by Lightning-64** [comment]
If this was a mod, I would use a loot modifier, but for KubeJs, modifying the existing loot tables directly as you have shown should work perfectly fine!
