### ISSUE TITLE
Chance to catch a Crate

### ISSUE THREAD

**Issue by zeroneon** [Lightning-64/Tide#30]
Is there a way to alter the chances of catching crates? I am having trouble finding anything at all related to that behaviour in the data folders. Maybe I am missing something though. I would hugely appreciate it if someone could point out where that might be
Forge and 1.20.1

**Comment by Lightning-64** [comment]
Currently there isn’t: it’s a 1/20 chance that becomes more likely depending on the player’s luck. Alternatively, if you use magnetic bait it becomes a 50% chance.

I can probably add this as a config setting in the mod for future updates though, if you want.

**Comment by zeroneon** [comment]
That would be hugely appreciated! Thank you very much.

**Comment by Lightning-64** [comment]
Added as of 1.3.4!
