### ISSUE TITLE
Custom Journal Profiles Duplicate When Using /reload

### ISSUE THREAD

**Issue by JasdewStarfield** [Lightning-64/Tide#31]
Minecraft : 1.20.1
Mod Loader: Forge 47.3.7
Tide : 1.3.3

When I add a profile by datapack like this:
![image](https://github.com/user-attachments/assets/52d094c1-d20b-438d-8d1f-a4be6dadbcfc)
The profile would duplicate in the journal:
![image](https://github.com/user-attachments/assets/552cdbcc-c677-48a5-9760-c4e803f273ef)
Additionally, if I exit the world and re-enter it, they would start doubling themselves...
![image](https://github.com/user-attachments/assets/235ff83b-08f5-42c3-9b20-f055b016dcd5)
I can be sure that this is not caused by myself writing the file twice, because when I delete the json file, both of the duplicates disappered.

**Comment by JasdewStarfield** [comment]
Using /reload will also cause these profiles to duplicate.

**Comment by Lightning-64** [comment]
Fixed as of 1.3.4!
