### ISSUE TITLE
Suggestion: Give Built-in Modded Support Fishes a Description (or Its Translation Key)

### ISSUE THREAD

**Issue by JasdewStarfield** [Lightning-64/Tide#32]
![image](https://github.com/user-attachments/assets/26d4340b-feff-47c3-9bc7-b3d42605f86c)
Like what's being written in this part of the code, the "Built-in" support for modded fishes does not contain the translation key of their descriptions, so it's impossible for someone who wants to write descriptions for them.
I hope that at least you can add an empty translation key for them, so it would be more convenient for modification!

**Comment by Lightning-64** [comment]
Added as of Tide 1.4.2!
