### ISSUE TITLE
why is aquaculture 2 not compatible? (neoforge 1.21.1 .76)

### ISSUE THREAD

**Issue by VaporeonScripts** [Lightning-64/Tide#38]

**Comment by VaporeonScripts** [comment]
Oh so I can use both with no problems?

**Comment by VaporeonScripts** [comment]
Like,it will work differently

**Comment by zeroneon** [comment]
You can use both no problem, yea

**Comment by Lightning-64** [comment]
Right; It’s not incompatible in the sense that it breaks, it’s just that aquaculture uses a similar system of mechanics.
