### ISSUE TITLE
[1.20.1 Forge 47.1.3] game crashes with this mod installed

### ISSUE THREAD

**Issue by TheChickenWizard** [Lightning-64/Tide#40]
Keeps crashing upon startup, all other mods I have work fine, including cloth, but once I add in this mod it just won't open for me. not sure what it could be incompatible with, again I had a lot of mods installed; maybe hybrid aquatic, Alex's mobs or any other mods that add fish to the game is the root of the issue?

**Comment by zeroneon** [comment]
Show your crash logs/mod list

**Comment by Lightning-64** [comment]
@TheChickenWizard if the issue is still happening, I would need to see your crash logs or I really can’t help.

**Comment by Lightning-64** [comment]
Closing because no crash logs were posted. If it still happens, let me know.
