### ISSUE TITLE
1.20.1 Crash with EasyNPC

### ISSUE THREAD

**Issue by PvtFudgepants** [Lightning-64/Tide#42]
While going through the Easy NPC menu I had my game crash. When looking at the log it looks like some interaction between Tide and EasyNPC

https://pastebin.com/Ar8byyVk

I have a ton of other mods, so I didn't get to check it with just those 2, but it seems to only happen when in the easynpc menu (specifically choosing a model and scrolling left and right)

**Comment by Lightning-64** [comment]
Fixed as of Tide 1.4.2
