### ISSUE TITLE
Angler's Workshop Doesn't Work

### ISSUE THREAD

**Issue by Goofert42** [Lightning-64/Tide#46]
Whenever players go to change something about their rod (eg. the hook) it doesn't actually change anything on the rod but still takes the item. There are no errors thrown in the servers console. Is anyone else experiencing this?

Mod Loader: Fabric
Game Version: 1.20.1
Mod Version: 1.3.3

https://github.com/user-attachments/assets/a61de2d1-97ac-48a6-917d-7b995d63e8a2

**Comment by moonfather1** [comment]
i can put a new hook just fine. 
forge loader, 1.3.3.

**Comment by Lightning-64** [comment]
Does updating to 1.3.4 fix this?
I’ve been in the process of re-doing rod upgrades though so if it doesn’t work in 1.3.4, it should be fixed in the next update.

**Comment by Goofert42** [comment]
Player reported another issue. The item doesn't get used up and stays in the workshop. I'll try to post a video of this.

**Comment by Lightning-64** [comment]
That's intentional, I wanted them to be able to be used multiple times so you didn't have to re-craft every time.
