### ISSUE TITLE
Fishing Journal not updating

### ISSUE THREAD

**Issue by AmaranthMoth** [Lightning-64/Tide#47]
From my understanding the fishing journal should update once you catch a new fish, but it hasn't been doing that and the reasons why elude me. 
Mod Loader: Fabric
Game Version: 1.20.1
Mod Version: 1.3.4
![2024-11-17_11 17 45](https://github.com/user-attachments/assets/3faec6e3-908f-4804-8dec-bc7a08d42dd2)

**Comment by moonfather1** [comment]
yeah, the interface is bad.

ignore the "check back here later" message that covers the whole screen. and click a small button in the right corner.

**Comment by AmaranthMoth** [comment]
Oh I did NOT see that okay thank you, you saved my life

**Comment by Lightning-64** [comment]
Yeah, maybe I should improve the interface lol. Sorry!
