### ISSUE TITLE
[1.20.1][Tooltip Crash]

### ISSUE THREAD

**Issue by POCKET-CATTT** [Lightning-64/Tide#51]
[crash-2024-12-15_03.58.08-client.txt](https://github.com/user-attachments/files/18137574/crash-2024-12-15_03.58.08-client.txt)

**Comment by Lightning-64** [comment]
Sorry about that! you can find the fixed version [here](https://modrinth.com/mod/tide/version/ac1nSfcO)

**Comment by POCKET-CATTT** [comment]
thank you
