### ISSUE TITLE
(Tide-fabric-1.20.1-1.4.0) Monster Spawners Missing Items

### ISSUE THREAD

**Issue by AlaxeSFM** [Lightning-64/Tide#52]
When this mod is installed. Even by itself with no other mods. Mobs that spawn from a Mob Spawner do not spawn with any equipment. Skeletons/strays have no bows, Vindicators have no axes, and so on.

**Comment by Lightning-64** [comment]
That's weird, considering Tide doesn't modify existing entities at all.
I'll have to look into this some more

**Comment by Lightning-64** [comment]
Fixed as of Tide 1.4.1!
