### ISSUE TITLE
Crash on server when interacting with rod

### ISSUE THREAD

**Issue by c6nvict** [Lightning-64/Tide#53]
The mod was working fine. I put some bait into the rod and then closed the server. I went to log onto the server today and everything works until interacting with the rod or opening my invetory. Here is the crash log:

https://pastebin.com/5xRbKzmm

**Comment by Lightning-64** [comment]
Make sure you're running the latest version. I put out 1-2 fixed versions (depending on modloader) for Tide 1.4.0 that fixed this specific issue, so I would assume that's the problem.
