### ISSUE TITLE
[1.20.1] High Lure Enchantment Stopping Fishing Event

### ISSUE THREAD

**Issue by AetheriMC** [Lightning-64/Tide#54]
Minecraft v1.20.1
Forge v47.3.0
Tide v1.4.0

**Issue**
Using a fishing rod with a Lure enchantment higher than 3 seems to break the fishing event, specifically preventing fish from ever biting. Originally noticed when using a rod with Lure VII. Once the rod's enchantment was reduced to Lure III, the issue was immediately resolved.

Image of the rod used (with Lure reduced to 3):
![image](https://github.com/user-attachments/assets/533446ef-3c4c-438a-9459-eafbe998bc48)

**Comment by Lightning-64** [comment]
Fixed as of Tide 1.4.2
