### ISSUE TITLE
[1.21.1 Fabric] Crash when dropping fishing rod at the same time as a fish bite

### ISSUE THREAD

**Issue by wowoyay** [Lightning-64/Tide#55]
Love the mod! I did discover a very easy to reproduce bug that crashes the game consistently. I have only tested this locally and on a LAN server. I am running Minecraft 1.21.1 with Fabric, and using the Fabric edition of Tide

Steps to reproduce:
 - Cast a line with any fishing rod (bait or not, doesn't matter)
 - Wait for a fish to bite
 - As the fish is biting (at the time you would right click to attempt to catch it), drop the fishing rod
 - The game crashes instantly

When loading back in, nothing is lost except for whatever fish you weren't able to catch, and you have dropped the rod on the ground so you can pick it back up.

Thanks!

**Comment by Lightning-64** [comment]
I'll try to have this fixed in the next update! I'm moving towards smaller and more periodic mod updates so it shouldn't take to long for me to add :)

**Comment by Lightning-64** [comment]
Fixed as of Tide 1.4.2
