### ISSUE TITLE
Removing a default fish journal profile

### ISSUE THREAD

**Issue by AStrangeMouse** [Lightning-64/Tide#9]
Now that profiles can be added to the Fishing Journal through data packs, is there a method to hide/remove default profiles?

For example, I've added a profile for the Bass from the Naturalist mod on the Freshwater page, however I haven't seen a way to remove this mod's own Bass profile, meaning there's two different Bass profiles on that page now.

**Comment by Lightning-64** [comment]
There currently isn't a way to do this, but I will make sure to add this in the next update.

**Comment by Lightning-64** [comment]
Added as of version 1.3.3! Info on the wiki on how to do this will be posted soon.
